# Generated by Django 5.0.6 on 2025-10-17 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_role_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
    ]
