# Generated by Django 5.0.6 on 2025-10-17 20:38

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_role_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordResetCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Fecha y hora en que se creó el registro', verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Fecha y hora de la última actualización', verbose_name='Fecha de actualización')),
                ('is_active', models.BooleanField(default=True, help_text='Indica si el registro está activo', verbose_name='Activo')),
                ('code', models.CharField(max_length=6, verbose_name='Código')),
                ('is_used', models.BooleanField(default=False, verbose_name='Usado')),
                ('expires_at', models.DateTimeField(verbose_name='Expira el')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='password_reset_codes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Código de restablecimiento de contraseña',
                'verbose_name_plural': 'Códigos de restablecimiento de contraseña',
                'ordering': ['-created_at'],
            },
        ),
    ]
