# Generated by Django 5.0.6 on 2025-09-24 03:18

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Fecha y hora en que se creó el registro', verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Fecha y hora de la última actualización', verbose_name='Fecha de actualización')),
                ('is_active', models.BooleanField(default=True, help_text='Indica si el registro está activo', verbose_name='Activo')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('department', models.CharField(max_length=50, verbose_name='Departamento')),
                ('city', models.CharField(max_length=50, verbose_name='Ciudad')),
                ('latitude', models.DecimalField(decimal_places=7, max_digits=10, verbose_name='Latitud')),
                ('longitude', models.DecimalField(decimal_places=7, max_digits=10, verbose_name='Longitud')),
                ('solar_irradiance', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Irradiación solar promedio (kWh/m²/día)')),
            ],
            options={
                'verbose_name': 'Ubicación',
                'verbose_name_plural': 'Ubicaciones',
            },
        ),
        migrations.CreateModel(
            name='SolarSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Fecha y hora en que se creó el registro', verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Fecha y hora de la última actualización', verbose_name='Fecha de actualización')),
                ('is_active', models.BooleanField(default=True, help_text='Indica si el registro está activo', verbose_name='Activo')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre del sistema')),
                ('system_type', models.CharField(choices=[('grid_tied', 'Conectado a la red'), ('off_grid', 'Aislado'), ('hybrid', 'Híbrido')], max_length=20, verbose_name='Tipo de sistema')),
                ('panel_power', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Potencia por panel (W)')),
                ('num_panels', models.IntegerField(verbose_name='Número de paneles')),
                ('inverter_efficiency', models.DecimalField(decimal_places=2, default=95.0, max_digits=4, verbose_name='Eficiencia del inversor (%)')),
                ('installation_cost', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Costo de instalación (COP)')),
                ('monthly_consumption', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Consumo mensual (kWh)')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simulator.location', verbose_name='Ubicación')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Sistema solar',
                'verbose_name_plural': 'Sistemas solares',
            },
        ),
        migrations.CreateModel(
            name='Simulation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Fecha y hora en que se creó el registro', verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Fecha y hora de la última actualización', verbose_name='Fecha de actualización')),
                ('is_active', models.BooleanField(default=True, help_text='Indica si el registro está activo', verbose_name='Activo')),
                ('simulation_date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de simulación')),
                ('monthly_generation', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Generación mensual (kWh)')),
                ('monthly_savings', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Ahorro mensual (COP)')),
                ('co2_avoided', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='CO2 evitado (kg)')),
                ('payback_period_years', models.DecimalField(decimal_places=1, max_digits=4, verbose_name='Período de retorno (años)')),
                ('solar_system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simulator.solarsystem', verbose_name='Sistema solar')),
            ],
            options={
                'verbose_name': 'Simulación',
                'verbose_name_plural': 'Simulaciones',
                'ordering': ['-simulation_date'],
            },
        ),
    ]
