# Generated by Django 5.0.6 on 2025-09-24 03:22

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegulatoryCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Fecha y hora en que se creó el registro', verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Fecha y hora de la última actualización', verbose_name='Fecha de actualización')),
                ('is_active', models.BooleanField(default=True, help_text='Indica si el registro está activo', verbose_name='Activo')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Categoría regulatoria',
                'verbose_name_plural': 'Categorías regulatorias',
            },
        ),
        migrations.CreateModel(
            name='RegulatoryDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Fecha y hora en que se creó el registro', verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Fecha y hora de la última actualización', verbose_name='Fecha de actualización')),
                ('is_active', models.BooleanField(default=True, help_text='Indica si el registro está activo', verbose_name='Activo')),
                ('title', models.CharField(max_length=300, verbose_name='Título')),
                ('document_number', models.CharField(max_length=50, verbose_name='Número de documento')),
                ('document_type', models.CharField(choices=[('law', 'Ley'), ('decree', 'Decreto'), ('resolution', 'Resolución'), ('circular', 'Circular'), ('standard', 'Norma técnica'), ('guideline', 'Lineamiento')], max_length=20, verbose_name='Tipo')),
                ('issuing_entity', models.CharField(max_length=200, verbose_name='Entidad emisora')),
                ('publication_date', models.DateField(verbose_name='Fecha de publicación')),
                ('effective_date', models.DateField(verbose_name='Fecha de vigencia')),
                ('summary', models.TextField(verbose_name='Resumen')),
                ('full_text', models.TextField(blank=True, verbose_name='Texto completo')),
                ('document_file', models.FileField(blank=True, null=True, upload_to='regulatory/', verbose_name='Archivo del documento')),
                ('external_url', models.URLField(blank=True, verbose_name='URL externa')),
                ('tags', models.CharField(blank=True, max_length=500, verbose_name='Etiquetas (separadas por comas)')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='regulatory.regulatorycategory', verbose_name='Categoría')),
            ],
            options={
                'verbose_name': 'Documento regulatorio',
                'verbose_name_plural': 'Documentos regulatorios',
                'ordering': ['-publication_date'],
            },
        ),
    ]
