# Generated by Django 5.0.6 on 2025-09-26 19:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regulatory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LegalFramework',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Fecha y hora en que se creó el registro', verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Fecha y hora de la última actualización', verbose_name='Fecha de actualización')),
                ('title', models.CharField(help_text='Título completo del documento legal', max_length=300, verbose_name='Título')),
                ('document_type', models.CharField(choices=[('ley', 'Ley'), ('decreto', 'Decreto'), ('resolucion', 'Resolución'), ('circular', 'Circular'), ('guia', 'Guía')], default='ley', max_length=20, verbose_name='Tipo de documento')),
                ('document_number', models.CharField(help_text='Ej: 1715, 2492, etc.', max_length=50, verbose_name='Número de documento')),
                ('year', models.PositiveIntegerField(help_text='Año de expedición', verbose_name='Año')),
                ('summary', models.TextField(help_text='Resumen en lenguaje claro y comprensible', verbose_name='Resumen')),
                ('main_objective', models.TextField(help_text='Objetivo principal de la norma', verbose_name='Objetivo principal')),
                ('benefits_companies', models.TextField(blank=True, help_text='Beneficios específicos para empresas', verbose_name='Beneficios para empresas')),
                ('benefits_citizens', models.TextField(blank=True, help_text='Beneficios específicos para ciudadanos', verbose_name='Beneficios para ciudadanos')),
                ('official_url', models.URLField(help_text='Enlace a la fuente oficial', verbose_name='URL oficial')),
                ('content_scraped', models.TextField(blank=True, help_text='Contenido obtenido mediante scraping', verbose_name='Contenido scrapeado')),
                ('last_scraped', models.DateTimeField(blank=True, null=True, verbose_name='Última actualización de scraping')),
                ('is_active', models.BooleanField(default=True, help_text='Si está activo para mostrar en el sitio', verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Marco Legal',
                'verbose_name_plural': 'Marcos Legales',
                'ordering': ['-year', 'document_number'],
            },
        ),
        migrations.CreateModel(
            name='ScrapingSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Fecha y hora en que se creó el registro', verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Fecha y hora de la última actualización', verbose_name='Fecha de actualización')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre de la fuente')),
                ('base_url', models.URLField(verbose_name='URL base')),
                ('selector_title', models.CharField(blank=True, max_length=200, verbose_name='Selector CSS para título')),
                ('selector_content', models.CharField(blank=True, max_length=200, verbose_name='Selector CSS para contenido')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Fuente de Scraping',
                'verbose_name_plural': 'Fuentes de Scraping',
            },
        ),
    ]
