# Generated by Django 5.0.6 on 2025-11-21 15:53

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educational', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Fecha y hora en que se creó el registro', verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Fecha y hora de la última actualización', verbose_name='Fecha de actualización')),
                ('is_active', models.BooleanField(default=True, help_text='Indica si el registro está activo', verbose_name='Activo')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('level', models.CharField(choices=[('basic', 'Básico'), ('intermediate', 'Intermedio'), ('advanced', 'Avanzado')], default='basic', max_length=15, verbose_name='Nivel')),
                ('estimated_hours', models.DecimalField(decimal_places=2, default=1.0, max_digits=5, verbose_name='Horas estimadas')),
                ('final_pass_score', models.PositiveIntegerField(default=70, help_text='Porcentaje mínimo para aprobar examen final', verbose_name='Puntaje aprobación examen final')),
                ('publish_state', models.CharField(choices=[('draft', 'Borrador'), ('published', 'Publicado'), ('archived', 'Archivado')], default='draft', max_length=10, verbose_name='Estado de publicación')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='courses', to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='educational.category', verbose_name='Categoría')),
            ],
            options={
                'verbose_name': 'Curso',
                'verbose_name_plural': 'Cursos',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Fecha y hora en que se creó el registro', verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Fecha y hora de la última actualización', verbose_name='Fecha de actualización')),
                ('is_active', models.BooleanField(default=True, help_text='Indica si el registro está activo', verbose_name='Activo')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('order', models.PositiveIntegerField(verbose_name='Orden')),
                ('summary', models.TextField(blank=True, verbose_name='Resumen')),
                ('required_pass_score', models.PositiveIntegerField(default=70, help_text='Porcentaje mínimo para aprobar el cuestionario del módulo', verbose_name='Puntaje mínimo')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='educational.course', verbose_name='Curso')),
            ],
            options={
                'verbose_name': 'Módulo',
                'verbose_name_plural': 'Módulos',
                'ordering': ['course', 'order'],
                'unique_together': {('course', 'order')},
            },
        ),
        migrations.CreateModel(
            name='ModuleAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Fecha y hora en que se creó el registro', verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Fecha y hora de la última actualización', verbose_name='Fecha de actualización')),
                ('is_active', models.BooleanField(default=True, help_text='Indica si el registro está activo', verbose_name='Activo')),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Inicio')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='Fin')),
                ('score', models.PositiveIntegerField(default=0, verbose_name='Puntaje (%)')),
                ('passed', models.BooleanField(default=False, verbose_name='Aprobado')),
                ('state', models.CharField(choices=[('in_progress', 'En progreso'), ('submitted', 'Enviado'), ('passed', 'Aprobado'), ('failed', 'Fallido')], default='in_progress', max_length=15, verbose_name='Estado')),
                ('attempt_number', models.PositiveIntegerField(default=1, verbose_name='Número de intento')),
                ('current_slide', models.PositiveIntegerField(default=1, verbose_name='Diapositiva actual')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='educational.module', verbose_name='Módulo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_attempts', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Intento de módulo',
                'verbose_name_plural': 'Intentos de módulo',
                'ordering': ['-started_at'],
                'unique_together': {('user', 'module', 'attempt_number')},
            },
        ),
        migrations.CreateModel(
            name='ModuleQuizQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Fecha y hora en que se creó el registro', verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Fecha y hora de la última actualización', verbose_name='Fecha de actualización')),
                ('is_active', models.BooleanField(default=True, help_text='Indica si el registro está activo', verbose_name='Activo')),
                ('text', models.TextField(verbose_name='Texto de la pregunta')),
                ('question_type', models.CharField(choices=[('single', 'Selección única'), ('multiple', 'Selección múltiple')], default='single', max_length=10, verbose_name='Tipo de pregunta')),
                ('explanation', models.TextField(blank=True, help_text='Retroalimentación mostrada tras responder', verbose_name='Explicación')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='educational.module', verbose_name='Módulo')),
            ],
            options={
                'verbose_name': 'Pregunta de módulo',
                'verbose_name_plural': 'Preguntas de módulo',
                'ordering': ['module', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='ModuleQuizOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Fecha y hora en que se creó el registro', verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Fecha y hora de la última actualización', verbose_name='Fecha de actualización')),
                ('is_active', models.BooleanField(default=True, help_text='Indica si el registro está activo', verbose_name='Activo')),
                ('text', models.CharField(max_length=300, verbose_name='Texto')),
                ('is_correct', models.BooleanField(default=False, verbose_name='Correcta')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='educational.modulequizquestion', verbose_name='Pregunta')),
            ],
            options={
                'verbose_name': 'Opción de pregunta',
                'verbose_name_plural': 'Opciones de pregunta',
                'ordering': ['question', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='CourseEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Fecha y hora en que se creó el registro', verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Fecha y hora de la última actualización', verbose_name='Fecha de actualización')),
                ('is_active', models.BooleanField(default=True, help_text='Indica si el registro está activo', verbose_name='Activo')),
                ('progress_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Progreso (%)')),
                ('all_modules_passed', models.BooleanField(default=False, verbose_name='Todos los módulos aprobados')),
                ('final_exam_unlocked', models.BooleanField(default=False, verbose_name='Examen final desbloqueado')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='educational.course', verbose_name='Curso')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_enrollments', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Inscripción de curso',
                'verbose_name_plural': 'Inscripciones de curso',
                'unique_together': {('user', 'course')},
            },
        ),
        migrations.CreateModel(
            name='ModuleAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Fecha y hora en que se creó el registro', verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Fecha y hora de la última actualización', verbose_name='Fecha de actualización')),
                ('is_active', models.BooleanField(default=True, help_text='Indica si el registro está activo', verbose_name='Activo')),
                ('is_correct', models.BooleanField(default=False, verbose_name='Correcta')),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='educational.moduleattempt', verbose_name='Intento')),
                ('selected_options', models.ManyToManyField(related_name='answers', to='educational.modulequizoption', verbose_name='Opciones seleccionadas')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='educational.modulequizquestion', verbose_name='Pregunta')),
            ],
            options={
                'verbose_name': 'Respuesta de módulo',
                'verbose_name_plural': 'Respuestas de módulo',
                'unique_together': {('attempt', 'question')},
            },
        ),
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Fecha y hora en que se creó el registro', verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Fecha y hora de la última actualización', verbose_name='Fecha de actualización')),
                ('is_active', models.BooleanField(default=True, help_text='Indica si el registro está activo', verbose_name='Activo')),
                ('order', models.PositiveIntegerField(verbose_name='Orden')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('content', models.TextField(help_text='HTML o Markdown del cuerpo de la diapositiva', verbose_name='Contenido')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slides', to='educational.module', verbose_name='Módulo')),
            ],
            options={
                'verbose_name': 'Diapositiva',
                'verbose_name_plural': 'Diapositivas',
                'ordering': ['module', 'order'],
                'unique_together': {('module', 'order')},
            },
        ),
    ]
