# Generated by Django 5.0.6 on 2025-11-21 16:03

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educational', '0002_course_module_moduleattempt_modulequizquestion_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FinalExamQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Fecha y hora en que se creó el registro', verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Fecha y hora de la última actualización', verbose_name='Fecha de actualización')),
                ('is_active', models.BooleanField(default=True, help_text='Indica si el registro está activo', verbose_name='Activo')),
                ('text', models.TextField(verbose_name='Texto de la pregunta')),
                ('question_type', models.CharField(choices=[('single', 'Selección única'), ('multiple', 'Selección múltiple')], default='single', max_length=10, verbose_name='Tipo de pregunta')),
                ('explanation', models.TextField(blank=True, verbose_name='Explicación')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='final_questions', to='educational.course', verbose_name='Curso')),
            ],
            options={
                'verbose_name': 'Pregunta examen final',
                'verbose_name_plural': 'Preguntas examen final',
                'ordering': ['course', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='FinalExamOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Fecha y hora en que se creó el registro', verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Fecha y hora de la última actualización', verbose_name='Fecha de actualización')),
                ('is_active', models.BooleanField(default=True, help_text='Indica si el registro está activo', verbose_name='Activo')),
                ('text', models.CharField(max_length=300, verbose_name='Texto')),
                ('is_correct', models.BooleanField(default=False, verbose_name='Correcta')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='final_options', to='educational.finalexamquestion', verbose_name='Pregunta')),
            ],
            options={
                'verbose_name': 'Opción examen final',
                'verbose_name_plural': 'Opciones examen final',
                'ordering': ['question', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='CourseCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Fecha y hora en que se creó el registro', verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Fecha y hora de la última actualización', verbose_name='Fecha de actualización')),
                ('is_active', models.BooleanField(default=True, help_text='Indica si el registro está activo', verbose_name='Activo')),
                ('issued_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Emitido')),
                ('certificate_code', models.CharField(max_length=60, unique=True, verbose_name='Código certificado')),
                ('final_score', models.PositiveIntegerField(default=0, verbose_name='Puntaje final')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Metadatos')),
                ('is_revoked', models.BooleanField(default=False, verbose_name='Revocado')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='educational.course', verbose_name='Curso')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_certificates', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Certificado de curso',
                'verbose_name_plural': 'Certificados de curso',
                'ordering': ['-issued_at'],
                'unique_together': {('user', 'course')},
            },
        ),
        migrations.CreateModel(
            name='FinalExamAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Fecha y hora en que se creó el registro', verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Fecha y hora de la última actualización', verbose_name='Fecha de actualización')),
                ('is_active', models.BooleanField(default=True, help_text='Indica si el registro está activo', verbose_name='Activo')),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Inicio')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='Fin')),
                ('score', models.PositiveIntegerField(default=0, verbose_name='Puntaje (%)')),
                ('passed', models.BooleanField(default=False, verbose_name='Aprobado')),
                ('state', models.CharField(choices=[('in_progress', 'En progreso'), ('submitted', 'Enviado'), ('passed', 'Aprobado'), ('failed', 'Fallido')], default='in_progress', max_length=15, verbose_name='Estado')),
                ('attempt_number', models.PositiveIntegerField(default=1, verbose_name='Número de intento')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='final_attempts', to='educational.course', verbose_name='Curso')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='final_exam_attempts', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Intento examen final',
                'verbose_name_plural': 'Intentos examen final',
                'ordering': ['-started_at'],
                'unique_together': {('user', 'course', 'attempt_number')},
            },
        ),
    ]
