# Generated by Django 5.0.6 on 2025-11-21 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educational', '0003_finalexamquestion_finalexamoption_coursecertificate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='max_final_attempts',
            field=models.PositiveIntegerField(default=0, help_text='0 = ilimitado', verbose_name='Máx intentos examen final'),
        ),
    ]
