# Generated by Django 5.0.6 on 2025-11-21 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educational', '0004_course_max_final_attempts'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursecertificate',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='certificates/', verbose_name='Archivo PDF'),
        ),
    ]
