# Generated by Django 5.0.6 on 2025-11-21 19:15

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educational', '0005_coursecertificate_pdf_file'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='slide',
            name='additional_resources',
            field=models.TextField(blank=True, help_text='Enlaces o referencias adicionales', verbose_name='Recursos adicionales'),
        ),
        migrations.AddField(
            model_name='slide',
            name='content_type',
            field=models.CharField(choices=[('text', 'Texto'), ('video', 'Video'), ('image', 'Imagen'), ('quiz', 'Quiz interactivo')], default='text', max_length=10, verbose_name='Tipo de contenido'),
        ),
        migrations.AddField(
            model_name='slide',
            name='duration_minutes',
            field=models.PositiveIntegerField(default=5, verbose_name='Duración estimada (min)'),
        ),
        migrations.AddField(
            model_name='slide',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='educational/slides/', verbose_name='Imagen'),
        ),
        migrations.AddField(
            model_name='slide',
            name='key_points',
            field=models.TextField(blank=True, help_text='Puntos principales separados por líneas', verbose_name='Puntos clave'),
        ),
        migrations.AddField(
            model_name='slide',
            name='subtitle',
            field=models.CharField(blank=True, max_length=300, verbose_name='Subtítulo'),
        ),
        migrations.AddField(
            model_name='slide',
            name='video_url',
            field=models.URLField(blank=True, help_text='YouTube, Vimeo, etc.', verbose_name='URL de video'),
        ),
        migrations.CreateModel(
            name='SlideView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Fecha y hora en que se creó el registro', verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Fecha y hora de la última actualización', verbose_name='Fecha de actualización')),
                ('is_active', models.BooleanField(default=True, help_text='Indica si el registro está activo', verbose_name='Activo')),
                ('viewed_at', models.DateTimeField(auto_now_add=True, verbose_name='Vista el')),
                ('time_spent_seconds', models.PositiveIntegerField(default=0, verbose_name='Tiempo dedicado (seg)')),
                ('completed', models.BooleanField(default=False, verbose_name='Completada')),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slide_views', to='educational.courseenrollment', verbose_name='Inscripción')),
                ('slide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='educational.slide', verbose_name='Diapositiva')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slide_views', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Vista de diapositiva',
                'verbose_name_plural': 'Vistas de diapositivas',
                'ordering': ['-viewed_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Fecha y hora en que se creó el registro', verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Fecha y hora de la última actualización', verbose_name='Fecha de actualización')),
                ('is_active', models.BooleanField(default=True, help_text='Indica si el registro está activo', verbose_name='Activo')),
                ('total_slides_viewed', models.PositiveIntegerField(default=0, verbose_name='Diapositivas vistas')),
                ('total_time_minutes', models.PositiveIntegerField(default=0, verbose_name='Tiempo total (min)')),
                ('modules_passed_count', models.PositiveIntegerField(default=0, verbose_name='Módulos aprobados')),
                ('quiz_attempts_count', models.PositiveIntegerField(default=0, verbose_name='Intentos de quiz')),
                ('exam_attempts_count', models.PositiveIntegerField(default=0, verbose_name='Intentos de examen')),
                ('best_exam_score', models.PositiveIntegerField(default=0, verbose_name='Mejor puntaje examen')),
                ('last_activity', models.DateTimeField(auto_now=True, verbose_name='Última actividad')),
                ('enrollment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='detailed_progress', to='educational.courseenrollment', verbose_name='Inscripción')),
            ],
            options={
                'verbose_name': 'Progreso de usuario',
                'verbose_name_plural': 'Progresos de usuario',
            },
        ),
        migrations.CreateModel(
            name='FinalExamAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Fecha y hora en que se creó el registro', verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Fecha y hora de la última actualización', verbose_name='Fecha de actualización')),
                ('is_active', models.BooleanField(default=True, help_text='Indica si el registro está activo', verbose_name='Activo')),
                ('is_correct', models.BooleanField(default=False, verbose_name='Correcta')),
                ('time_spent_seconds', models.PositiveIntegerField(default=0, verbose_name='Tiempo dedicado (seg)')),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='educational.finalexamattempt', verbose_name='Intento')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='educational.finalexamquestion', verbose_name='Pregunta')),
                ('selected_options', models.ManyToManyField(related_name='answers', to='educational.finalexamoption', verbose_name='Opciones seleccionadas')),
            ],
            options={
                'verbose_name': 'Respuesta examen final',
                'verbose_name_plural': 'Respuestas examen final',
                'unique_together': {('attempt', 'question')},
            },
        ),
    ]
