# Generated by Django 5.0.6 on 2025-10-17 19:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blogreport_blogreaction'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='blogreport',
            name='processed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de procesamiento'),
        ),
        migrations.AddField(
            model_name='blogreport',
            name='processed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blog_reports_processed', to=settings.AUTH_USER_MODEL, verbose_name='Procesado por'),
        ),
        migrations.AlterField(
            model_name='blogreport',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('in_review', 'En revisión'), ('resolved', 'Resuelto'), ('dismissed', 'Descartado')], default='pending', max_length=20, verbose_name='Estado'),
        ),
    ]
