# Generated by Django 5.0.6 on 2025-09-24 03:22

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('simulator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnergyReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Fecha y hora en que se creó el registro', verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Fecha y hora de la última actualización', verbose_name='Fecha de actualización')),
                ('is_active', models.BooleanField(default=True, help_text='Indica si el registro está activo', verbose_name='Activo')),
                ('reading_date', models.DateTimeField(verbose_name='Fecha de lectura')),
                ('energy_generated', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Energía generada (kWh)')),
                ('energy_consumed', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Energía consumida (kWh)')),
                ('energy_exported', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Energía exportada (kWh)')),
                ('solar_system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simulator.solarsystem', verbose_name='Sistema solar')),
            ],
            options={
                'verbose_name': 'Lectura de energía',
                'verbose_name_plural': 'Lecturas de energía',
                'ordering': ['-reading_date'],
            },
        ),
        migrations.CreateModel(
            name='MonthlyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Fecha y hora en que se creó el registro', verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Fecha y hora de la última actualización', verbose_name='Fecha de actualización')),
                ('is_active', models.BooleanField(default=True, help_text='Indica si el registro está activo', verbose_name='Activo')),
                ('year', models.IntegerField(verbose_name='Año')),
                ('month', models.IntegerField(verbose_name='Mes')),
                ('total_generated', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Total generado (kWh)')),
                ('total_consumed', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Total consumido (kWh)')),
                ('total_savings', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Ahorro total (COP)')),
                ('co2_avoided', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='CO2 evitado (kg)')),
                ('solar_system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simulator.solarsystem', verbose_name='Sistema solar')),
            ],
            options={
                'verbose_name': 'Reporte mensual',
                'verbose_name_plural': 'Reportes mensuales',
                'ordering': ['-year', '-month'],
                'unique_together': {('solar_system', 'year', 'month')},
            },
        ),
    ]
